server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/lingua_hub?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: trungdev234@gmail.com
    password: ehfd fjkm jbom aktq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

  jackson:
    time-zone: Asia/Ho_Chi_Minh

google:
  client-id: "42781484149-pel6vfv7rb7ih298ru93t6vq1fg8q3sq.apps.googleusercontent.com"

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.mail: DEBUG

jwt:
  signerKey: "1TjXchw5FLOEsb63KcDFhTARvPWL4jUGCWfGWxgSS1f/1y/LgJxHnMqaF6A/ijXY"

vietqr:
  bank-code: "970422"
  account-no: "0964472908"
  account-name: "NGUYEN DUC TRUNG"

mbbank:
  account-no: "0964472908"
  authorization: "Basic RU1CUkVUQUlMV0VCOlNEMjM0ZGZnMzQlI0BGR0AzNHNmc2RmNDU4NDNm"
  cookie: "AKA_A2=A; _ga=GA1.3.1336235301.1762984700; _gid=GA1.3.1382435629.1762984700; _fbp=fb.2.1762984700494.336948940903920783; MBAnalyticsaaaaaaaaaaaaaaaa_session_=IPNLIPKPMHEAEHOCEJEIGHCKFCICGHJMHELNMHLIOPFAIBHOFEEKOGNIPLKFDGPGACLDOOKPCFJPBIJKFCBAHPFEDAEEEAFPHMDLKLIJGMKBPOBHEFMMHBKHOOOBNJEK; MBAnalytics2142333981aaaaaaaaaaaaaaaa_cspm_=IOIEIJKBONPBBMOFDAECCDLALLPGNKEEAPAFILEENONHFPMGLLHOOLPCLOIJAJLNKFJCOGIKCMCLNPAMPANADLPFFJOIPCNKFJBDFHCDICNOCKHKHHLDCMCDHGLHAHDJ; JSESSIONID=2A97D5E459EB2001882922F583FA8022; mbbank=3474718986.7466.0000"

scheduler:
  enabled: true
